# utils/emojis.py
"""Centralized Emoji Registry for the Nexus Event Bot."""

# Common Status Indicators
SUCCESS = "✅"
ERROR = "❌"
INFO = "💡"
WARNING = "⚠️"

# UI Elements & Navigation
DROPDOWN_OPEN = "🔽"
DROPDOWN_CLOSED = "◀️"
GEAR = "⚙️"
GLOBE = "🌐"
PEOPLE = "👥"
CLONE = "👯"
ADD = "➕"
CLOCK = "⏰"
TIME = "🕒"
LIST = "📋"
WIZARD = "✨"
DRAFT = "📝"
SHIELD = "🛡️"
BELL = "🔔"
PING = "📢"
SYNC = "🔄"
CROSS = "✖️"
HELP = "❓"
TOOLS = "🛠️"
PRESENCE = "🎮"
PIN = "📌"
WAIT = "⏳"
CALENDAR = "📅"
GEM = "💎"
CRYSTAL = "🔮"
STAR = "⭐"
HERB = "🌿"
FLOWER = "🌸"
PALETTE = "🎨"
TROPHY = "🏆"
HEADPHONES = "🎧"
EYES = "👀"
BOT = "🤖"
SATELLITE = "🛰️"
EDIT = "✏️"
DELETE = "🗑️"
BACK = "◀️"
LANG_HU = "🇭🇺"
LANG_EN = "🇺🇸"
PACKAGE = "📦"
TV = "📺"

# Recurrence Types
REC_DAILY = "📅"
REC_WEEKLY = "🗓️"
REC_MONTHLY = "📊"
REC_BIWEEKLY = "🔄"
REC_WEEKDAYS = "🏢"
REC_WEEKENDS = "🏖️"
REC_CUSTOM = "⚙️"
REC_RELATIVE = "📆"

def get_all_emojis():
    """Returns a dictionary of all uppercase constants defined in this module."""
    return {k: v for k, v in globals().items() if k.isupper() and isinstance(v, str)}
